title: GitHub Customization Guide
author: Paulo Sánchez
theme: minima
email: szblzpaulo@gmail.com
description: >
    A complete guide for GitHub READMEs customization.

github_username:  erlete

show_excerpts: true
