title: GitHub Customization Guide
author: Paulo Sánchez
theme: minima
email: szblzpaulo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    A complete guide for GitHub READMEs customization.

# social links
github_username:  erlete # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
